---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tracing
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.47
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        # --- Cambios para el almacenamiento persistente con Badger ---
        - name: SPAN_STORAGE_TYPE
          value: "badger"
        - name: BADGER_EPHEMERAL
          value: "false"
        - name: BADGER_DIRECTORY_VALUE
          value: "/badger/data"
        - name: BADGER_DIRECTORY_KEY
          value: "/badger/key"
        # ------------------------------------------------------------
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
        - containerPort: 14250
          name: grpc
        - containerPort: 14267
          name: c-tchan-trft
        - containerPort: 14268
          name: c-binary-trft
        - containerPort: 16686
          name: query
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
          - name: jaeger-storage
            mountPath: /badger  # Montamos el directorio raíz para Badger
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
      volumes:
        - name: jaeger-storage
          persistentVolumeClaim:
            claimName: jaeger-pvc
