apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: https://github.com/Nettaro-Consulting/gke-argocd.git
    targetRevision: main
    path: tracing
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
